version: '3.6'

services:
  sample.chathub.api:
    image: ${DOCKER_REGISTRY-}samplechathub
    restart: unless-stopped
    container_name: sample-chathub.api
    build:
      context: .
      dockerfile: src/Server/Sample.ChatHub.API/Dockerfile

  cache:
    image: redis
    container_name: sample-chathub-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: --loglevel warning
    volumes: 
      - cache:/data
    
  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    container_name: sample-chathub-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: sample-chathub-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - /home/Docker/Volumes/MongoDB:/data/db
